openapi: 3.0.3
info:
  title: FineFoods
  version: 1.0.0
servers:
  - url: https://api.finefoods.refine.dev/
paths:
  /products:
    get:
      summary: Find product
      description: Find a product
      operationId: listProducts
      responses:
        200:
          description: success
      parameters:
        - name: description_like
          in: query
          schema:
            type: string
