openapi: 3.0.3
info:
  title: FineFoods
  version: 1.0.0
servers:
  - url: https://api.finefoods.refine.dev
paths:
  /products:
    get:
      summary: Find product
      description: Find a product
      operationId: listProducts
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
      parameters:
        - name: description_like
          in: query
          schema:
            type: string
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        isActive:
          type: boolean
        description:
          type: string
        createdAt:
          type: string
          format: date-time
        price:
          type: integer
        category:
          type: object
          properties:
            id:
              type: integer
        images:
          type: array
          items:
            $ref: '#/components/schemas/Image'
    Image:
      type: object
      properties:
        url:
          type: string
        thumbnailUrl:
          type: string
        name:
          type: string
        status:
          type: string
        type:
          type: string
        uid: 
          type: string
